[package]
name = "render"
description = "Push environment variables to render.com"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
reqwest = {version = "0.11.7", features = ["blocking"]}
serde = {version = "1.0.130", optional = false, features = ["derive"]}
serde_json = {version = "1.0.72", optional = false}
